name: Build and Publish

on: push

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            7.0.x
            6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal
        env:
          OriginalTurboBoat: ${{ secrets.ORIGINALTURBOBOAT }}

      - name: Pack
        if: github.ref_name == 'stable' || github.ref_name == 'alpha'
        run: |
          dotnet pack NetCord -c Release --no-restore --no-build
          dotnet pack NetCord.Services -c Release --no-restore --no-build

      - name: Publish
        if: github.ref_name == 'stable' || github.ref_name == 'alpha'
        run: dotnet nuget push NetCord/**.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --no-symbols && (dotnet nuget push NetCord.Services/**.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --no-symbols; echo 'PUSHED=1' >> $GITHUB_ENV || true) || (dotnet nuget push NetCord.Services/**.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --no-symbols && echo 'PUSHED=1' >> $GITHUB_ENV || true)

      - name: Build Documentation
        if: env.PUSHED == 1
        run: |
          dotnet tool install docfx -g --version 2.61
          cd Documentation
          docfx

      - name: Stop Apache2
        if: env.PUSHED == 1
        uses: appleboy/ssh-action@v0.1.7
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: sudo systemctl stop apache2

      - name: Deploy Documentation
        if: env.PUSHED == 1
        uses: appleboy/scp-action@v0.1.3
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          rm: true
          source: Documentation/_site
          strip_components: 2
          target: ~/NetCord/html

      - name: Start Apache2
        if: env.PUSHED == 1
        uses: appleboy/ssh-action@v0.1.7
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: sudo systemctl start apache2